name: ffmpeg encode

on:
  push:

  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-latest

    env:
      BOTAPI: ${{ secrets.BOTAPI }}
      CHATID: ${{ secrets.CHATID }}
      GHSECRET: ${{ secrets.GHSECRET }}

    steps:
      - name: Clone
        run: git clone --depth 1 https://github.com/realraf37/ffmpeg_encode_wf -b exp && cd ffmpeg_encode_wf

      - name: Trigger script
        run: |
          bash ffmpeg.sh
