name: ffmpeg encode

on:
  push:

  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-latest

    env:
      BOTAPI: ${{ secrets.BOTAPI }}
      CHATID: ${{ secrets.CHATID }}
      GHSECRET: ${{ secrets.GHSECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Trigger script
        run: |
          bash f-new.sh
